### PR TITLE
Generate premake5 for libavformat

### PR DESCRIPTION
**Pull request by Hendi48**
This PR makes it possible to build libavformat so we can have WMA file parsing.

### CODE REVIEW

**Comment by Gliniak** [comment]
Just fyi: I tried to build it and it failed on missing files: 	
protocol_list.c, muxer_list.c, demuxer_list.c

Also XMP also can decode mp3 files, so I guess you should add that too

**Comment by Hendi48** [comment]
My bad, I didn't realize those need to be committed because they are in gitignore. I also added mp3 decoding.

**Comment by antoniodesousa** [comment]
Hopefully this gets merged soon so @Hendi48 can continue working on the XMP implementation.

**Comment by Hendi48** [comment]
> Hopefully this gets merged soon so @Hendi48 can continue working on the XMP implementation.

This MR isn't blocking me from doing further work. I'm waiting for Gliniak to publish his code since it sounded more fleshed out w.r.t. playback control.

**Comment by antoniodesousa** [comment]
Ah I see, I hope that @Gliniak shares the code with you soon then. I'm really looking forward to see XMP be implemented in Xenia. Like you, I was really disappointed to find out that Burnout Revenge needed this for the music to play.

**Pull request merged**
